### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by shenweima** [AshokHub/locBLAST#1]
Hi, I find a your blast tool from here. But I don't know why it is not work for me.
I also add my local database to db file, but they were not found in web page.
Could you help me?
![2019-05-09 17-33-18](https://user-images.githubusercontent.com/8536868/57443592-feef8080-7280-11e9-97c7-07d1dc783956.gif)
![image](https://user-images.githubusercontent.com/8536868/57443793-6d344300-7281-11e9-82b1-eb4912cdadb8.png)

**Comment by AshokHub** [comment]
I found that you are using Linux OS. You must provide **access permission to the locBLAST folder** using **sudo chmod -R 777 locBLAST** command before testing the tool.

**Comment by shenweima** [comment]
I think I have gave these files access permission
[image](https://user-images.githubusercontent.com/8536868/57496004-664e1480-7303-11e9-9c0b-35a493526f4e.png)
Like first time, there is still no response when I click "search" button.

**Comment by AshokHub** [comment]
I run the program on **Microsoft Windows 10** operating system with **PHP Version 7.3.5** in web server. It works fine. The only possible chances is with the PHP version, shown in the snapshot.

If you are using lower PHP version, replace the conditional statement with following lines (**for Linux**):

```
$osextn = "";
$osstrt = "./";
```

## Working Demo

[![GIF](http://www.biogem.org/downloads/github/BLAST.jpg)](http://www.biogem.org/downloads/github/BLAST.gif)

OR

[![WMV](http://www.biogem.org/downloads/github/BLAST.jpg)](http://www.biogem.org/downloads/github/BLAST.wmv)

**Comment by shenweima** [comment]
Thanks for your answer. Yes, my server is centos 7. I have updated php version and restart apache server. But, it still not work.
If you know docker , you can make a docker image. It's good for people who wants to use this web blast.
Thank you again!

![image](https://user-images.githubusercontent.com/8536868/57499687-2bec7380-7313-11e9-998f-86e59aa9f65f.png)

**Comment by AshokHub** [comment]
Did you tried the code changes below?

```
$osextn = "";
$osstrt = "./";
```

**Comment by AshokHub** [comment]
I am not familiar with Docker.
If still problem exists, give few days time to run through Linux through VMware and i'll conclude.

**Comment by shenweima** [comment]
```
$osextn = "";
$osstrt = "./";
```
The code is not changed because it is same with code in index.php
![image](https://user-images.githubusercontent.com/8536868/57516861-28bfaa80-7348-11e9-8755-a9700ffc07c6.png)

**Comment by DesarrolladorCII** [comment]
Hi, Ashok Kumar T.
Thank you very much for sharing your knowledge. I have the same problem that does not work the search used the demo, I am in ubuntu 16.04.
regards

**Comment by AshokHub** [comment]
I have tested in Linux server. It works.
Just do the following changes in **index.php** file, for Linux OS. Lines to replace: **246** to **260**

![1](https://user-images.githubusercontent.com/843713/57638611-c5de4580-75cb-11e9-9cd0-8d564acaa30f.jpg)
 
to

![2](https://user-images.githubusercontent.com/843713/57638642-d0004400-75cb-11e9-984a-5835bf3aef0e.jpg)

**Comment by DesarrolladorCII** [comment]
Thanks for answering AshokHub, I will prove it

**Comment by AshokHub** [comment]
Best Wishes. I'll soon find a solution for OS compatibility issues.

**Comment by DesarrolladorCII** [comment]
I'm sorry, I still have problems. I get this error Invalid Input / Program / Database Selection!
Select the DEMO option and search button

**Comment by AshokHub** [comment]
Do changes as mentioned before. I have not updated in GitHub repository. You must do changes in your **index.php** file.

![2019-05-13_223356](https://user-images.githubusercontent.com/843713/57640214-700b9c80-75cf-11e9-882a-5cec482f29d3.jpg)

Demo: http://118.25.192.119/locBLAST/index.php

**Comment by shenweima** [comment]
Thanks, it works. I want to use my local db. But, I am failed.
This is my local db (six_plant).
![image](https://user-images.githubusercontent.com/8536868/57663439-90b31100-7626-11e9-8a24-b4f4d1ba35e1.png)
And I changed the code in the index.php for using my local db.
![image](https://user-images.githubusercontent.com/8536868/57663572-22228300-7627-11e9-891f-e96dd2aa3f79.png)

 But,  I can't find that in web page.
![image](https://user-images.githubusercontent.com/8536868/57663642-5f871080-7627-11e9-8281-96409a253bb3.png)


> Do changes as mentioned before. I have not updated in GitHub repository. You must do changes in your **index.php** file.
> 
> ![2019-05-13_223356](https://user-images.githubusercontent.com/843713/57640214-700b9c80-75cf-11e9-882a-5cec482f29d3.jpg)
> 
> Demo: http://118.25.192.119/locBLAST/index.php
> Source Code: http://www.biogem.org/downloads/github/index.txt

**Comment by shenweima** [comment]
I think I have known how to change code in index.php and footer.php.
However, I think this is not very simple.
Maybe you can refer viroblast which give a viroblast.ini file. [viroblast](https://github.com/MullinsLab/ViroblastStandalone)

**Comment by AshokHub** [comment]
@shenweima Thank you for you valuable feedback. I have planned to release new version **locBLAST v3.0** with rich features mimic to NCBI BLAST. My aim is to design user-friendly interface with **_no manual configuration_**. For the time being, i'll do changes for your custom **db** through FTP.
