### ISSUE TITLE
File Creation Failed!

### ISSUE THREAD

**Issue by Jungal10** [AshokHub/locBLAST#3]
Hello,
First, thank you for creating an intuitive usage for BLAST for it can be locally run.
I have integrated your BLAST in my website that will host an upcoming Genome Browser.

I can make it online. Although, I did not manage to generate a blast result.

Every time I click "Search" I get "File Creation Failed!"

So, I cannot make the tool usable. Any help on this end you can offer me? You can find it [here](https://amaranthgdb.org/blast.html)

Thanks

**Comment by AshokHub** [comment]
Grant permission to the locBLAST folder using `sudo chmod -R 777 locBLAST` command.
